services:
  orders-service:
    build: orders/.
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - USERS-URL=users-service
      - PRODUCTS-URL=products-service
      - DB_HOST=postgres-service
      - DB_NAME=online-shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres-service
      - users-service
      - products-service

  users-service:
    build: users/.
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres-service
      - DB_NAME=online-shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres-service

  products-service:
    build: products/.
    ports:
      - "7070:7070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres-service
      - DB_NAME=online-shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres-service

  postgres-service:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=online-shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres